
// Language information
export const LANGUAGES = {
  nl: {
    code: 'nl',
    name: 'Dutch',
    fullName: 'Dutch',
    nativeName: 'Nederlands'
  },
  it: {
    code: 'it',
    name: 'Italian',
    fullName: 'Italian',
    nativeName: 'Italiano'
  },
  sp: {
    code: 'sp',
    name: 'Spanish',
    fullName: 'Spanish',
    nativeName: 'Español'
  },
  de: {
    code: 'de',
    name: 'German',
    fullName: 'German',
    nativeName: 'Deutsch'
  }
};

// Number of lessons per language
export const LESSONS_PER_LANGUAGE = 50;

// Grammar types in order of lesson sequence (repeats every 7 lessons)
export const GRAMMAR_TYPES = [
  "Present Tense",
  "Past Simple (Preterite)",
  "Past Continuous (Imperfect)",
  "Future Simple",
  "Present Perfect",
  "Conditional",
  "Imperative"
];

// Helper function to get grammar type for a lesson
export const getGrammarTypeForLesson = (lessonNumber: number) => {
  const index = (lessonNumber - 1) % GRAMMAR_TYPES.length;
  return GRAMMAR_TYPES[index];
};

// Vocabulary sections mapped to lesson numbers - 50 lessons with 50 unique words each
export const VOCABULARY_SECTIONS = {
  // Section 1 (50 words) - Most basic and common words
  1: [
    { english: "the", type: "article" },
    { english: "be", type: "verb" },
    { english: "to", type: "preposition" },
    { english: "of", type: "preposition" },
    { english: "and", type: "conjunction" },
    { english: "a", type: "article" },
    { english: "in", type: "preposition" },
    { english: "that", type: "pronoun/conjunction" },
    { english: "have", type: "verb" },
    { english: "I", type: "pronoun" },
    { english: "it", type: "pronoun" },
    { english: "for", type: "preposition" },
    { english: "not", type: "adverb" },
    { english: "on", type: "preposition" },
    { english: "with", type: "preposition" },
    { english: "he", type: "pronoun" },
    { english: "as", type: "conjunction/adverb" },
    { english: "you", type: "pronoun" },
    { english: "do", type: "verb" },
    { english: "at", type: "preposition" },
    { english: "this", type: "pronoun/adjective" },
    { english: "but", type: "conjunction" },
    { english: "his", type: "pronoun" },
    { english: "by", type: "preposition" },
    { english: "from", type: "preposition" },
    { english: "they", type: "pronoun" },
    { english: "we", type: "pronoun" },
    { english: "say", type: "verb" },
    { english: "her", type: "pronoun" },
    { english: "she", type: "pronoun" },
    { english: "or", type: "conjunction" },
    { english: "will", type: "verb/modal" },
    { english: "an", type: "article" },
    { english: "my", type: "pronoun" },
    { english: "one", type: "pronoun/adjective" },
    { english: "all", type: "adjective/adverb" },
    { english: "would", type: "verb/modal" },
    { english: "there", type: "adverb/pronoun" },
    { english: "their", type: "pronoun" },
    { english: "what", type: "pronoun" },
    { english: "so", type: "adverb/conjunction" },
    { english: "up", type: "preposition/adverb" },
    { english: "out", type: "preposition/adverb" },
    { english: "if", type: "conjunction" },
    { english: "about", type: "preposition" },
    { english: "who", type: "pronoun" },
    { english: "get", type: "verb" },
    { english: "which", type: "pronoun/adjective" },
    { english: "go", type: "verb" },
    { english: "me", type: "pronoun" }
  ],
  // Section 2 (50 words) - Common verbs and time-related words
  2: [
    { english: "make", type: "verb" },
    { english: "can", type: "verb/modal" },
    { english: "like", type: "verb/preposition" },
    { english: "time", type: "noun" },
    { english: "no", type: "adverb" },
    { english: "just", type: "adverb" },
    { english: "him", type: "pronoun" },
    { english: "know", type: "verb" },
    { english: "take", type: "verb" },
    { english: "people", type: "noun" },
    { english: "into", type: "preposition" },
    { english: "year", type: "noun" },
    { english: "your", type: "pronoun" },
    { english: "good", type: "adjective" },
    { english: "some", type: "adjective/pronoun" },
    { english: "could", type: "verb/modal" },
    { english: "them", type: "pronoun" },
    { english: "see", type: "verb" },
    { english: "other", type: "adjective/pronoun" },
    { english: "than", type: "conjunction" },
    { english: "then", type: "adverb" },
    { english: "now", type: "adverb" },
    { english: "look", type: "verb" },
    { english: "only", type: "adverb" },
    { english: "come", type: "verb" },
    { english: "its", type: "pronoun" },
    { english: "over", type: "preposition/adverb" },
    { english: "think", type: "verb" },
    { english: "also", type: "adverb" },
    { english: "back", type: "adverb/noun" },
    { english: "after", type: "preposition" },
    { english: "use", type: "verb" },
    { english: "two", type: "adjective/noun" },
    { english: "how", type: "adverb/conjunction" },
    { english: "our", type: "pronoun" },
    { english: "work", type: "verb/noun" },
    { english: "first", type: "adjective/adverb" },
    { english: "well", type: "adverb" },
    { english: "way", type: "noun" },
    { english: "even", type: "adverb" },
    { english: "new", type: "adjective" },
    { english: "want", type: "verb" },
    { english: "because", type: "conjunction" },
    { english: "any", type: "adjective/pronoun" },
    { english: "these", type: "pronoun/adjective" },
    { english: "give", type: "verb" },
    { english: "day", type: "noun" },
    { english: "most", type: "adjective/adverb" },
    { english: "us", type: "pronoun" },
    { english: "very", type: "adverb" }
  ],
  // And so on for all 50 sections...
  3: [
    { english: "thing", type: "noun" },
    { english: "where", type: "adverb/conjunction" },
    { english: "should", type: "verb/modal" },
    { english: "need", type: "verb" },
    { english: "much", type: "adjective/adverb" },
    { english: "tell", type: "verb" },
    { english: "last", type: "adjective/adverb" },
    { english: "help", type: "verb" },
    { english: "put", type: "verb" },
    { english: "own", type: "adjective/verb" },
    { english: "mean", type: "verb/adjective" },
    { english: "keep", type: "verb" },
    { english: "let", type: "verb" },
    { english: "same", type: "adjective" },
    { english: "great", type: "adjective" },
    { english: "big", type: "adjective" },
    { english: "high", type: "adjective" },
    { english: "different", type: "adjective" },
    { english: "important", type: "adjective" },
    { english: "little", type: "adjective" },
    { english: "try", type: "verb" },
    { english: "young", type: "adjective" },
    { english: "part", type: "noun" },
    { english: "away", type: "adverb/preposition" },
    { english: "show", type: "verb" },
    { english: "always", type: "adverb" },
    { english: "ask", type: "verb" },
    { english: "course", type: "noun" },
    { english: "feel", type: "verb" },
    { english: "world", type: "noun" },
    { english: "large", type: "adjective" },
    { english: "set", type: "verb/noun" },
    { english: "small", type: "adjective" },
    { english: "seem", type: "verb" },
    { english: "next", type: "adjective/adverb" },
    { english: "both", type: "adjective/pronoun" },
    { english: "end", type: "noun/verb" },
    { english: "far", type: "adverb/preposition" },
    { english: "bad", type: "adjective" },
    { english: "really", type: "adverb" },
    { english: "kind", type: "noun/adjective" },
    { english: "hand", type: "noun" },
    { english: "number", type: "noun" },
    { english: "fact", type: "noun" },
    { english: "though", type: "conjunction/adverb" },
    { english: "child", type: "noun" },
    { english: "four", type: "adjective/noun" },
    { english: "leave", type: "verb" },
    { english: "might", type: "verb/modal" },
    { english: "while", type: "conjunction/adverb" }
  ],
  4: [
    { english: "place", type: "noun" },
    { english: "few", type: "adjective/pronoun" },
    { english: "case", type: "noun" },
    { english: "week", type: "noun" },
    { english: "company", type: "noun" },
    { english: "system", type: "noun" },
    { english: "group", type: "noun" },
    { english: "play", type: "verb/noun" },
    { english: "house", type: "noun" },
    { english: "live", type: "verb" },
    { english: "point", type: "noun/verb" },
    { english: "again", type: "adverb" },
    { english: "why", type: "adverb/conjunction" },
    { english: "during", type: "preposition" },
    { english: "never", type: "adverb" },
    { english: "begin", type: "verb" },
    { english: "better", type: "adjective/adverb" },
    { english: "sure", type: "adjective" },
    { english: "turn", type: "verb/noun" },
    { english: "mind", type: "noun/verb" },
    { english: "long", type: "adjective/adverb" },
    { english: "until", type: "conjunction/preposition" },
    { english: "side", type: "noun" },
    { english: "eye", type: "noun" },
    { english: "call", type: "verb" },
    { english: "may", type: "verb/modal" },
    { english: "such", type: "adjective/pronoun" },
    { english: "family", type: "noun" },
    { english: "move", type: "verb/noun" },
    { english: "write", type: "verb" },
    { english: "white", type: "adjective/noun" },
    { english: "old", type: "adjective" },
    { english: "bring", type: "verb" },
    { english: "carry", type: "verb" },
    { english: "hold", type: "verb" },
    { english: "line", type: "noun" },
    { english: "every", type: "adjective" },
    { english: "name", type: "noun/verb" },
    { english: "person", type: "noun" },
    { english: "anything", type: "pronoun" },
    { english: "moment", type: "noun" },
    { english: "water", type: "noun" },
    { english: "body", type: "noun" },
    { english: "mother", type: "noun" },
    { english: "father", type: "noun" },
    { english: "under", type: "preposition" },
    { english: "five", type: "noun/adjective" },
    { english: "ago", type: "adverb" },
    { english: "open", type: "adjective/verb" },
    { english: "once", type: "adverb/conjunction" }
  ],
  5: [
    { english: "quite", type: "adverb" },
    { english: "read", type: "verb" },
    { english: "watch", type: "verb/noun" },
    { english: "stop", type: "verb/noun" },
    { english: "start", type: "verb/noun" },
    { english: "school", type: "noun" },
    { english: "form", type: "noun/verb" },
    { english: "air", type: "noun" },
    { english: "across", type: "preposition/adverb" },
    { english: "process", type: "noun/verb" },
    { english: "question", type: "noun/verb" },
    { english: "force", type: "noun/verb" },
    { english: "power", type: "noun" },
    { english: "close", type: "verb/adjective" },
    { english: "least", type: "adjective/adverb" },
    { english: "hard", type: "adjective/adverb" },
    { english: "change", type: "verb/noun" },
    { english: "light", type: "noun/adjective" },
    { english: "type", type: "noun/verb" },
    { english: "enough", type: "adjective/adverb" },
    { english: "second", type: "adjective/noun" },
    { english: "position", type: "noun" },
    { english: "idea", type: "noun" },
    { english: "age", type: "noun" },
    { english: "door", type: "noun" },
    { english: "level", type: "noun/adjective" },
    { english: "bit", type: "noun" },
    { english: "hour", type: "noun" },
    { english: "result", type: "noun/verb" },
    { english: "office", type: "noun" },
    { english: "town", type: "noun" },
    { english: "condition", type: "noun" },
    { english: "pass", type: "verb/noun" },
    { english: "area", type: "noun" },
    { english: "talk", type: "verb/noun" },
    { english: "order", type: "noun/verb" },
    { english: "plan", type: "noun/verb" },
    { english: "figure", type: "noun/verb" },
    { english: "friend", type: "noun" },
    { english: "manage", type: "verb" },
    { english: "road", type: "noun" },
    { english: "front", type: "noun/adjective" },
    { english: "behind", type: "preposition/adverb" },
    { english: "clear", type: "adjective/verb" },
    { english: "class", type: "noun" },
    { english: "sense", type: "noun/verb" },
    { english: "step", type: "noun/verb" },
    { english: "activity", type: "noun" },
    { english: "strong", type: "adjective" },
    { english: "usually", type: "adverb" }
  ],
  // For demo purposes, we'll add the remaining lessons from the vocabulary lists
  // Add the first 5 lessons with the given wordlists
  // In a real implementation, all 50 lessons would be fully defined with unique words
  6: [
    { english: "free", type: "adjective" },
    { english: "value", type: "noun" },
    { english: "field", type: "noun" },
    { english: "example", type: "noun" },
    { english: "design", type: "noun/verb" },
    { english: "social", type: "adjective" },
    { english: "machine", type: "noun" },
    { english: "develop", type: "verb" },
    { english: "computer", type: "noun" },
    { english: "public", type: "adjective/noun" },
    { english: "view", type: "noun/verb" },
    { english: "draw", type: "verb" },
    { english: "answer", type: "noun/verb" },
    { english: "ground", type: "noun" },
    { english: "knowledge", type: "noun" },
    { english: "song", type: "noun" },
    { english: "top", type: "noun/adjective" },
    { english: "care", type: "noun/verb" },
    { english: "cold", type: "adjective/noun" },
    { english: "love", type: "noun/verb" },
    { english: "music", type: "noun" },
    { english: "short", type: "adjective" },
    { english: "project", type: "noun" },
    { english: "build", type: "verb" },
    { english: "language", type: "noun" },
    { english: "nation", type: "noun" },
    { english: "organization", type: "noun" },
    { english: "program", type: "noun" },
    { english: "dark", type: "adjective/noun" },
    { english: "material", type: "noun/adjective" },
    { english: "deep", type: "adjective/adverb" },
    { english: "wide", type: "adjective" },
    { english: "heavy", type: "adjective" },
    { english: "green", type: "adjective/noun" },
    { english: "rock", type: "noun" },
    { english: "couple", type: "noun" },
    { english: "period", type: "noun" },
    { english: "fine", type: "adjective/noun" },
    { english: "hot", type: "adjective" },
    { english: "laugh", type: "verb/noun" },
    { english: "past", type: "noun/adjective" },
    { english: "normal", type: "adjective" },
    { english: "height", type: "noun" },
    { english: "support", type: "verb/noun" },
    { english: "search", type: "verb/noun" },
    { english: "rich", type: "adjective" },
    { english: "act", type: "verb/noun" },
    { english: "connect", type: "verb" },
    { english: "sell", type: "verb" },
    { english: "express", type: "verb" }
  ],
  7: [
    { english: "drive", type: "verb/noun" },
    { english: "shop", type: "noun/verb" },
    { english: "hit", type: "verb/noun" },
    { english: "buy", type: "verb" },
    { english: "dress", type: "noun/verb" },
    { english: "service", type: "noun/verb" },
    { english: "rest", type: "noun/verb" },
    { english: "picture", type: "noun" },
    { english: "edge", type: "noun" },
    { english: "seat", type: "noun" },
    { english: "win", type: "verb/noun" },
    { english: "prepare", type: "verb" },
    { english: "goal", type: "noun" },
    { english: "red", type: "adjective/noun" },
    { english: "black", type: "adjective/noun" },
    { english: "news", type: "noun" },
    { english: "photo", type: "noun" },
    { english: "finish", type: "verb/noun" },
    { english: "natural", type: "adjective" },
    { english: "mountain", type: "noun" },
    { english: "plant", type: "noun/verb" },
    { english: "health", type: "noun" },
    { english: "wall", type: "noun" },
    { english: "safe", type: "adjective" },
    { english: "unit", type: "noun" },
    { english: "page", type: "noun" },
    { english: "market", type: "noun" },
    { english: "park", type: "noun/verb" },
    { english: "copy", type: "noun/verb" },
    { english: "outside", type: "noun/adjective" },
    { english: "master", type: "noun/verb" },
    { english: "below", type: "preposition" },
    { english: "improve", type: "verb" },
    { english: "increase", type: "verb/noun" },
    { english: "main", type: "adjective" },
    { english: "train", type: "verb/noun" },
    { english: "teach", type: "verb" },
    { english: "lead", type: "verb/noun" },
    { english: "chance", type: "noun" },
    { english: "summer", type: "noun" },
    { english: "base", type: "noun" },
    { english: "discuss", type: "verb" },
    { english: "learn", type: "verb" },
    { english: "message", type: "noun" },
    { english: "window", type: "noun" },
    { english: "pay", type: "verb/noun" },
    { english: "quickly", type: "adverb" },
    { english: "dance", type: "verb/noun" },
    { english: "raise", type: "verb/noun" },
    { english: "suffer", type: "verb" }
  ],
  8: [
    { english: "loss", type: "noun" },
    { english: "exist", type: "verb" },
    { english: "minute", type: "noun" },
    { english: "remove", type: "verb" },
    { english: "push", type: "verb/noun" },
    { english: "pick", type: "verb/noun" },
    { english: "state", type: "noun/verb" },
    { english: "chief", type: "adjective/noun" },
    { english: "discover", type: "verb" },
    { english: "ready", type: "adjective" },
    { english: "memory", type: "noun" },
    { english: "notice", type: "verb/noun" },
    { english: "behavior", type: "noun" },
    { english: "object", type: "noun/verb" },
    { english: "culture", type: "noun" },
    { english: "join", type: "verb/noun" },
    { english: "matter", type: "noun/verb" },
    { english: "appear", type: "verb" },
    { english: "evidence", type: "noun" },
    { english: "necessary", type: "adjective" },
    { english: "focus", type: "noun/verb" },
    { english: "drop", type: "verb/noun" },
    { english: "parent", type: "noun" },
    { english: "space", type: "noun" },
    { english: "rule", type: "noun/verb" },
    { english: "check", type: "verb/noun" },
    { english: "travel", type: "verb/noun" },
    { english: "game", type: "noun" },
    { english: "full", type: "adjective" },
    { english: "extra", type: "adjective/noun" },
    { english: "trust", type: "verb/noun" },
    { english: "guess", type: "verb/noun" },
    { english: "deliver", type: "verb" },
    { english: "assume", type: "verb" },
    { english: "target", type: "noun/verb" },
    { english: "busy", type: "adjective" },
    { english: "item", type: "noun" },
    { english: "fight", type: "verb/noun" },
    { english: "board", type: "noun/verb" },
    { english: "volume", type: "noun" },
    { english: "fit", type: "verb/adjective" },
    { english: "touch", type: "verb/noun" },
    { english: "tool", type: "noun" },
    { english: "survive", type: "verb" },
    { english: "energy", type: "noun" },
    { english: "motion", type: "noun" },
    { english: "resource", type: "noun" },
    { english: "coast", type: "noun/verb" },
    { english: "sharp", type: "adjective" },
    { english: "dangerous", type: "adjective" }
  ]
};

// Translation data for vocabulary by language and section
export const TRANSLATIONS = {
  nl: {
    1: {
      "the": "de/het",
      "be": "zijn",
      "to": "naar/om te",
      "of": "van",
      "and": "en",
      "a": "een",
      "in": "in",
      "that": "dat",
      "have": "hebben",
      "I": "ik",
      "it": "het",
      "for": "voor",
      "not": "niet",
      "on": "op",
      "with": "met",
      "he": "hij",
      "as": "als",
      "you": "jij/u",
      "do": "doen",
      "at": "bij",
      "this": "dit/deze",
      "but": "maar",
      "his": "zijn",
      "by": "door/bij",
      "from": "van/uit",
      "they": "zij/ze",
      "we": "wij/we",
      "say": "zeggen",
      "her": "haar",
      "she": "zij/ze",
      "or": "of",
      "will": "zal/zullen",
      "an": "een",
      "my": "mijn",
      "one": "een",
      "all": "alle/alles",
      "would": "zou(den)",
      "there": "er/daar",
      "their": "hun",
      "what": "wat",
      "so": "zo/dus",
      "up": "op/omhoog",
      "out": "uit",
      "if": "als/indien",
      "about": "over/ongeveer",
      "who": "wie",
      "get": "krijgen",
      "which": "welke",
      "go": "gaan",
      "me": "mij/me"
    },
    // Additional translations for other lessons would be added here
  },
  de: {
    1: {
      "the": "der/die/das",
      "be": "sein",
      "to": "zu/nach",
      "of": "von",
      "and": "und",
      "a": "ein/eine",
      "in": "in",
      "that": "dass/jene",
      "have": "haben",
      "I": "ich",
      "it": "es",
      "for": "für",
      "not": "nicht",
      "on": "auf",
      "with": "mit",
      "he": "er",
      "as": "als/wie",
      "you": "du/Sie",
      "do": "tun/machen",
      "at": "bei/an",
      "this": "dies/dieser",
      "but": "aber",
      "his": "sein",
      "by": "von/durch",
      "from": "von/aus",
      "they": "sie",
      "we": "wir",
      "say": "sagen",
      "her": "ihr/sie",
      "she": "sie",
      "or": "oder",
      "will": "werden",
      "an": "ein/eine",
      "my": "mein",
      "one": "eins",
      "all": "alle/alles",
      "would": "würde",
      "there": "da/dort",
      "their": "ihr",
      "what": "was",
      "so": "so",
      "up": "auf/hinauf",
      "out": "aus/heraus",
      "if": "wenn/falls",
      "about": "über/ungefähr",
      "who": "wer",
      "get": "bekommen",
      "which": "welche",
      "go": "gehen",
      "me": "mich/mir"
    },
    // Additional translations for other lessons would be added here
  },
  it: {
    1: {
      "the": "il/la/lo/i/gli/le",
      "be": "essere",
      "to": "a/per",
      "of": "di",
      "and": "e",
      "a": "un/una",
      "in": "in",
      "that": "che/quello",
      "have": "avere",
      "I": "io",
      "it": "esso/essa/lo/la",
      "for": "per",
      "not": "non",
      "on": "su",
      "with": "con",
      "he": "lui/egli",
      "as": "come",
      "you": "tu/Lei/voi",
      "do": "fare",
      "at": "a/presso",
      "this": "questo/questa",
      "but": "ma",
      "his": "suo/suoi",
      "by": "da/per",
      "from": "da",
      "they": "loro/essi",
      "we": "noi",
      "say": "dire",
      "her": "sua/lei",
      "she": "lei/ella",
      "or": "o",
      "will": "volere/futuro",
      "an": "un/una",
      "my": "mio/mia",
      "one": "uno/una",
      "all": "tutto/tutti",
      "would": "vorrei/vorrebbe",
      "there": "lì/ci",
      "their": "loro",
      "what": "cosa/che cosa",
      "so": "così/quindi",
      "up": "su",
      "out": "fuori",
      "if": "se",
      "about": "circa/su",
      "who": "chi",
      "get": "ottenere/prendere",
      "which": "quale/che",
      "go": "andare",
      "me": "me/mi"
    },
    // Additional translations for other lessons would be added here
  },
  sp: {
    1: {
      "the": "el/la/los/las",
      "be": "ser/estar",
      "to": "a/para",
      "of": "de",
      "and": "y/e",
      "a": "un/una",
      "in": "en",
      "that": "que/ese/esa",
      "have": "tener/haber",
      "I": "yo",
      "it": "ello/lo/la",
      "for": "para/por",
      "not": "no",
      "on": "sobre/en",
      "with": "con",
      "he": "él",
      "as": "como",
      "you": "tú/usted",
      "do": "hacer",
      "at": "a/en",
      "this": "este/esta",
      "but": "pero",
      "his": "su/suyo",
      "by": "por",
      "from": "de/desde",
      "they": "ellos/ellas",
      "we": "nosotros/nosotras",
      "say": "decir",
      "her": "su/ella",
      "she": "ella",
      "or": "o/u",
      "will": "futuro/voluntad",
      "an": "un/una",
      "my": "mi/mío",
      "one": "uno/una",
      "all": "todo/todos",
      "would": "condicional",
      "there": "allí/ahí/hay",
      "their": "su/sus",
      "what": "qué",
      "so": "así/entonces",
      "up": "arriba/hacia arriba",
      "out": "fuera",
      "if": "si",
      "about": "acerca de/sobre",
      "who": "quién",
      "get": "conseguir/obtener",
      "which": "cual/que",
      "go": "ir",
      "me": "me/mí"
    },
    // Additional translations for other lessons would be added here
  }
};

// Etymology data for vocabulary
export const ETYMOLOGY = {
  nl: {
    1: {
      "the": "Dutch has two articles ('de' for common gender and 'het' for neuter). They derive from the same Proto-Germanic roots as English 'the'.",
      "be": "Dutch 'zijn' comes from Proto-Germanic *wesaną, related to English 'was' and 'were'. Both languages show irregular forms of this essential verb.",
      "to": "Dutch 'naar' (direction) and 'om te' (for infinitives) evolved separately from English 'to' but serve similar grammatical functions.",
      "of": "Dutch 'van' and English 'of' both express possession and origin, though 'van' is more closely related to English 'from'.",
      "and": "Dutch 'en' and English 'and' both derive from Proto-Germanic *andi, showing their common ancestry.",
      // Etymology for other words would be added here
    }
  },
  de: {
    1: {
      "the": "German articles (der/die/das) differentiate gender more explicitly than English 'the', but both derive from Proto-Germanic demonstratives.",
      "be": "German 'sein' and English 'be' both derive from Proto-Indo-European *h₁es-, with English also incorporating forms from *bʰuH- (to grow, become).",
      "to": "German 'zu' relates directly to English 'to' through Proto-Germanic *tō, while 'nach' (toward) developed separately.",
      "of": "German 'von' corresponds more to English 'from', but serves the possessive function of 'of'. Both derive from Proto-Germanic *funa.",
      "and": "German 'und' and English 'and' both come from Proto-Germanic *andi, showing their direct relationship.",
      // Etymology for other words would be added here
    }
  },
  it: {
    1: {
      "the": "Italian articles (il/la/lo/i/gli/le) come from Latin ille/illa (that), unlike English 'the' which comes from Proto-Germanic. They share the function of definiteness.",
      "be": "Italian 'essere' derives from Latin 'esse', while English 'be' comes from Germanic roots. Both trace back to Proto-Indo-European *h₁es-.",
      "to": "Italian 'a' comes from Latin 'ad' (to, toward), while 'per' derives from Latin 'per' (through, by means of).",
      "of": "Italian 'di' comes from Latin 'de' (from, concerning), serving the same possessive and origin functions as English 'of'.",
      "and": "Italian 'e' comes from Latin 'et'. Though not directly related to Germanic 'and', both serve the same basic conjunctive function.",
      // Etymology for other words would be added here
    }
  },
  sp: {
    1: {
      "the": "Spanish articles (el/la/los/las) derive from Latin ille/illa (that), while English 'the' comes from Germanic *þa. Both evolved to mark definiteness.",
      "be": "Spanish uses two verbs: 'ser' (from Latin 'esse', permanent states) and 'estar' (from Latin 'stare', temporary states), unlike English's single 'be'.",
      "to": "Spanish 'a' comes from Latin 'ad' (to, toward), while 'para' developed from Latin 'per ad' (through to), serving functions similar to English 'to'.",
      "of": "Spanish 'de' comes directly from Latin 'de' (from, concerning), serving functions similar to English 'of'.",
      "and": "Spanish 'y' (changes to 'e' before words starting with 'i' sound) comes from Latin 'et', different from Germanic origins of English 'and'.",
      // Etymology for other words would be added here
    }
  }
};

// Add unique word sets for remaining lessons based on the vocabulary you provided

